apiVersion: v2
name: accelerator
description: A Helm chart for deployment of the Accelerator infrastructure

type: application
sources:
  - https://github.com/NIEHS/accelerator-helm
  - https://github.com/apache/airflow
  - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
  - https://github.com/bitnami/charts/tree/main/bitnami/mongodb

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
- name: mongodb
  version: ~16.5.1
  repository: "https://charts.bitnami.com/bitnami"
- name: airflow 
  version:  ~1.16.0
  repository: "https://airflow.apache.org/"

