apiVersion: v2
name: accelerator
description: A Helm chart for deployment of the Accelerator infrastructure
type: application

version: "0.1.3"        # ⬅️ REQUIRED: chart version (semver)
appVersion: "1.16.3"    # optional: your app version

sources:
  - https://github.com/NIEHS/accelerator-helm
  - https://github.com/apache/airflow
  - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/mongodb

dependencies:
  #- name: mongodb
  #  version: "~0.6.6"
  #  repository: "https://cloudpirates-io.github.io/helm-charts"

  - name: mongodb
    version: ~18.1.10
    repository: "https://charts.bitnami.com/bitnami"

  - name: postgres 
    version: "~0.12.4"
    repository: "https://cloudpirates-io.github.io/helm-charts"

  - name: airflow 
    version: "~1.18.0"
    repository: "https://airflow.apache.org/"
