apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: excom-pvc
  namespace: accelerator   # change if needed
spec:
  volumeName: excom-pv        # 👈 forces the binding
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
